### ISSUE TITLE
Efterlev Googles policy för användares medgivande inom EU

### ISSUE THREAD

**Issue by bonny** [bonny/texttv.nu-website#27]
Måste lägga in cookie-ruta antar jag.

Mailet från Google:
https://mail.google.com/mail/u/0/#all/CXKnWZngLGgsFgtMrghjLDsHBjSHWJBfpwBDdvB

Lite mer info:

- https://support.google.com/admob/answer/7666519?hl=sv
- https://support.google.com/admob/answer/9035987?hl=sv
- https://www.google.com/intl/sv/about/company/user-consent-policy-help/
- https://support.google.com/adsense/answer/7549925?hl=sv

## Todo

- [x] Skapa sida med cookie-info, https://texttv.nu/sida/cookies
- [x] Skriv & lägg in text
- [x] Skapa ruta som lägger sig längst ner på sidan fixed, pga mest mobila användare = nära tummen/fingret
- [x] Ok-knapp som sätter cookie, göm ruta om cookie är satt
- [ ] Vänta och se om Google godkänner vår lösning

## Exempel på sidors cookie-policy

- https://ikeamuseum.com/sv/anvandarvillkor/cookiepolicy/
- https://svemarknad.se/kontakt/personuppgifts/
- https://www.prv.se/sv/om-oss/om-webbplatsen/
- https://www.svenskaturistforeningen.se/om-stf/cookies/

## Kakor som används på texttv.nu

- stats
- __gads
- _gid
- _ga

## Rubriker att ha med på mer-info-sidan

- Vad är en kaka
- Hur tar jag bort en kaka
- Vilka kakor används

## Exempel på texter

Exempel från Google:

> Får vi använda din data till att skräddarsy annonser åt dig?
> Våra partner samlar in och använder cookies till annonsanpassning och mätning. Läs mer om hur [webbplatsens namn] och våra 10 partner samlar in och använder data

--- 

Exempel 2 från Google:

> Innan du fortsätter till Google Sök
> Google använder cookies och data för att
> leverera och underhålla våra tjänster – till exempel att spåra avbrott och skydda mot spam, bedrägerier och otillåten användning
> registrera målgruppsengagemang och webbplatsstatistik så att vi kan analysera hur våra tjänster används
> Om du godkänner använder vi även cookies och data för att
> förbättra våra tjänster och utveckla nya
> leverera annonser och mäta hur effektiva de är
> visa anpassat innehåll utifrån dina inställningar
> visa anpassade eller allmänna annonser på Google och på andra webbplatser utifrån dina inställningar
> Utan anpassning kan innehåll och annonser väljas ut utifrån sådant som vad du tittar på nu och var du befinner dig (annonsvisning baseras på platsen där du befinner dig). Med anpassning kan innehåll och annonser väljas ut utifrån ovanstående och dessutom utifrån din aktivitet, t.ex. vad du har sökt efter på Google och vilka videor på YouTube du har tittat på. Anpassning av innehåll och annonser ger till exempel mer relevanta resultat och rekommendationer, en anpassad startsida på YouTube och annonser som bygger på dina intressen.

---

Exempel från STF.se:

> Cookies kommer ihåg vem du är så att du kan få en bättre upplevelse. Genom att använda denna hemsida eller stänga denna ruta godkänner du cookies.
> Läs mer om cookies här. 

---

Exempel från https://www.svenskaturistforeningen.se/:

> Vi använder cookies för att ge dig bästa möjliga upplevelse. Fortsätter du använda webbplatsen accepterar du att cookies används. Läs mer

---

Exempel från SVT.se:

> Vi har placerat cookies på din dator och lagrar din IP-adress för att ge dig en bättre upplevelse av våra webbplatser. Om du inte godkänner eller vill ha mer information kan du läsa mer här: Om cookies och personuppgifter

---

Exempel från IkeaMuseum.se

> IKEA Museums webbplats använder cookies som gör den enklare att använda. Läs mer om vår cookie policy och personuppgiftspolicy.

--- 

Exempel från DagensMedicin.se

> Vi använder cookies för att förbättra funktionaliteten på våra sajter, för att kunna rikta relevant innehåll och annonser till dig och för att vi ska kunna säkerställa att tjänsterna fungerar som de ska.

> [Läs mer] [Stäng]

**Comment by bonny** [comment]
Stänger denna pga använder [Google Funding Choices](https://fundingchoices.google.com/) för att visa cookie-rutan.
